import Coulmn from "@/components/Column";
import FAB from "@/components/FAB";
import { TodoContext } from "@/context/TodoContext";
import Head from "next/head";
import { useContext } from "react";

export default function Home() {
  const { } = useContext(TodoContext);
  return (
    <>
      <Head>
        <title>Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex gap-8 justify-center min-h-screen mt-8">
        <Coulmn status={'todo'} name={"Todo"} />
        <Coulmn status={'inProgress'} name="In Progress" />
        <Coulmn status={'done'} name="Done" />
        <FAB />
      </main>
    </>
  );
}
